version: '3'

services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: challenge-app
    container_name: challenge-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www
    networks:
      - challenge-network
    command: php artisan serve --host=0.0.0.0

  db:
    image: mysql:8.0
    container_name: challenge-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - challenge-network

networks:
  challenge-network:
    driver: bridge
